### ISSUE TITLE
Few doubts regarding your model. 

### ISSUE THREAD

**Issue by sanchit2843** [sachinsdate/lip-movement-net#2]
Sir, I have two doubts regarding your model as it is not working for the test video. 
1. How is the pixel separation calculated, in your code, I found it was euclidean distance, is it right?
2. What is label 0 for and label 1 for, in your readme, it was written speech and silence respectively but most prediction I got were opposite? 
Regards.

**Comment by AnkyZhang** [comment]
I have the same question with you, have you known the answers? Thanks in advance.

**Comment by sanchit2843** [comment]
Sorry but I am not sure about the answers.
